---
- hosts: targets
  tasks:
    - name: System updates
      package:
        name: "*"
        state: latest
    - name: Install development tools
      package:
        name: "@Development Tools"
        state: latest
    - name: Install ncurses-devel
      package:
        name: ncurses-devel
        state: latest
    - name: Install qt-devel
      package:
        name: qt-devel
        state: latest
    - name: Install hmaccalc
      package:
        name: hmaccalc
        state: latest
    - name: Install zlib-devel
      package:
        name: zlib-devel
        state: latest
    - name: Install binutils-devel
      package:
        name: binutils-devel
        state: latest
    - name: Install elfutils-libelf-devel
      package:
        name: elfutils-libelf-devel
        state: latest

